default_stages: [commit, push]
fail_fast: true
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.2
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: "0.3.4"
    hooks:
      # Run the pip compile
      - id: pip-compile
        args: [pyproject.toml, -o, requirements.txt]
