[tool.poetry]
name = "slackutils"
version = "0.2.1"
description = ""
authors = ["nagomiso <daiseigi.giants+github@gmail.com>"]
license = "MIT License"
readme = "README.md"
packages = [{ include = "slackutils", from = "src/" }]

[tool.poetry.dependencies]
python = "^3.10"
slack-sdk = "^3.19.5"
click = "^8.1.3"
s3fs = "^2022.11.0"

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"
black = "^22.12.0"
flake8 = "^6.0.0"
mypy = "^0.991"
isort = "^5.11.3"
pre-commit = "^2.20.0"

[tool.poetry.scripts]
slackutils = "slackutils.cmd.main:main"

[tool.black]
line-length = 88
target-version = ["py310"]

[tool.isort]
profile = "black"
include_trailing_comma = true
line_length = 88
multi_line_output = 3
use_parentheses = true
known_third_party = "slack_sdk"
known_first_party = "slackutils"

[tool.pytest.ini_options]
minversion = "7.2"
addopts = """
    -s \
    -vv"""
testpaths = ["tests"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
