[tool.poetry]
name = "slackutils"
version = "0.2.0"
description = ""
authors = ["nagomiso <daiseigi.giants+github@gmail.com>"]
license = "MIT License"

[tool.poetry.dependencies]
python = "^3.8"
slack-sdk = "^3.9.1"
click = "^8.0.1"
s3fs = "^2021.4.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
black = "^21.7b0"
flake8 = "^3.9.0"
mypy = "^0.910"
isort = "^5.9.3"
pre-commit = "^2.14.0"

[tool.poetry.scripts]
slackutils = "slackutils.cmd.main:main"

[tool.black]
line-length = 88
target-version = ["py38"]

[tool.isort]
profile = "black"
include_trailing_comma = true
line_length = 88
multi_line_output = 3
use_parentheses = true
known_third_party = "slack_sdk"
known_first_party = "slackutils"

[tool.pytest.ini_options]
minversion = "6.2"
addopts = """
    -s \
    -vv"""
testpaths = ["tests"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
