name: Docker Image Build
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
env:
  POETRY_VERSION: "1.7.1"
  IMG_TAG: pr-${{ github.event.number }}
jobs:
  lint_and_build:
    name: Lint and Build Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Poetry
        run: |
          pipx install poetry==${{ env.POETRY_VERSION }}
      - name: Run poetry install
        run: poetry install
      - name: Lint
        run: |
          poetry run pre-commit run -a
      - name: Build wheel
        run: |
          poetry build -f wheel
          mkdir -p docker/wheels && cp -a dist/*.whl docker/wheels/
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: docker
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:nightly
            ghcr.io/${{ github.repository }}:${{ env.IMG_TAG }}
