name: Docker Image Build
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
env:
  POETRY_VERSION: "1.1.7"
  TAG: pr-${{ github.event.number }}
jobs:
  lint_and_build:
    name: Lint and Build Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install Poetry
        run: |
          pip3 install --user poetry==${{ env.POETRY_VERSION }}
      - name: Run poetry install
        run: poetry install
      - name: Lint
        run: |
          poetry run pip install -U pip setuptools wheel
          poetry run pre-commit run -a
      - name: Build wheel
        run: |
          poetry build -f wheel
          mkdir -p docker/wheels && cp -a dist/*.whl docker/wheels/
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: docker
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:nightly
            ghcr.io/${{ github.repository }}:${{ env.TAG }}
