name: Docker Image Build
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
env:
  BUILD_VERSION: "1.2.1"
  IMG_TAG: pr-${{ github.event.number }}
jobs:
  lint_and_build:
    name: Lint and Build Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.5"
      - name: Install pre-commit
        run:
          pipx install pre-commit --python 3.12.5
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Run pre-commit
        run: pre-commit run --all-files
      - name: Install Build
        run: |
          pip3.12 install build==${{ env.BUILD_VERSION }}
      - name: Build wheel
        run: |
          python3.12 -m build --wheel .
          mkdir -p docker/wheels && cp -a dist/*.whl docker/wheels/
      - uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1
      - uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85 # v6.7.0
        with:
          context: docker
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:nightly
            ghcr.io/${{ github.repository }}:${{ env.IMG_TAG }}
