name: Release
on:
  pull_request:
    types:
      - closed
env:
  DASEL_VERSION: v2.0.2
  IMG_TAG: pr-${{ github.event.number }}
jobs:
  release:
    name: Release a new version
    runs-on: ubuntu-22.04
    if: |
      github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'release')
    steps:
      - uses: actions/checkout@v2
      - name: Install dasel
        run: |
          sudo curl -L \
            https://github.com/TomWright/dasel/releases/download/${{ env.DASEL_VERSION }}/dasel_linux_amd64 \
            -o /usr/local/bin/dasel
          sudo chmod +x /usr/local/bin/dasel
      - name: Get a release version
        run: |
          echo "RELEASE_VERSION=v$(dasel -f pyproject.toml -r toml .tool.poetry.version)" >> $GITHUB_ENV
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a new tag
        run: |
          git tag ${{ env.RELEASE_VERSION }}
          git push origin ${{ env.RELEASE_VERSION }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
      - name: Release a image
        run: |
          docker pull ghcr.io/${{ github.repository }}:${{ env.IMG_TAG }}
          docker tag \
            ghcr.io/${{ github.repository }}:${{ env.IMG_TAG }} \
            ghcr.io/${{ github.repository }}:${{ env.RELEASE_VERSION }}
          docker push ghcr.io/${{ github.repository }}:${{ env.RELEASE_VERSION }}
          docker tag \
            ghcr.io/${{ github.repository }}:${{ env.IMG_TAG }} \
            ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:latest
